title: lyfe-Hacker
subtitle: Personal Portfolio of Shan-tk
description: >- # this means to ignore newlines until "baseurl:"
  Fix hard-coded [object Object] string (thanks!)4

url: "https://shan.infozy.tk" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Shop
      url : /shop
    - text: Contact Me
      url : /contact

# Edit these details

author_logo: profile.png
about_me_photo: about_me.jpg
author: Shan-tk
author_bio: A long time ago, in a galaxy far far away...whoooooooooooooooooooooooo...
author_email: "tksudharshan@infozy.tk"
author_location: India
author_website_url: "http://infozy.tk"
typewrite-text: "*insert pretentious stuff about myself here*.TODO: Tell someone to implement this"

author_work_experiences:
            - company_name: Ford Rhodes Parks LLP
              company_logo: ca.png
              company_url: https://fordrhodesparks.com
              designation: Article Assistant
              description: Working as a CA Intern.
              visibility: true

author_education_details:
              - college_logo: icai.png
                college_name: ICAI
                college_url: https://icai.org
                college_degree: CA Inter
                description: Chartered Accountancy - Intermediate - Pursuing CA Final Course
                visibility: true

author_project_details:
              - project_thumbnail: infozy.png
                project_title: Infozy IIG website
                project_description: A Platform built for Sharing Valuable Information
                project_url: https://infozy.tk
                visibility: true
              - project_thumbnail: flash_chat.png
                project_title: Flash Chat
                project_description: Flutter based Chat App.
                project_url: https://github.com/tks18
                visibility: true

# social links
twitter_username: shantk18
github_username:  tks18
facebook_username: 
linkedin_username: shantk18
behance_username: sudharshantk
instagram_username: shantk18
medium_username: shantk18
telegram_username: Shan_tk
dribbble_username: Sudhar2000
flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname:
hyvor_talk_website_id: 656

# wakatime username (coding activity)
wakatime_username: shantk18

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://formspree.io/tksudharshan@gmail.com

# formspree (contact form)
formspree_email: tksudharshan@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: infozy_tk # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
